import {PrimeVueLocaleOptions} from '@primevue/core/config';
import {definePreset} from '@primevue/themes';
import Aura from '@primevue/themes/aura';
import colors from 'tailwindcss/colors';

const localeTr: PrimeVueLocaleOptions = {
    startsWith: 'İle Başla',
    contains: 'İçerir',
    notContains: 'İçermez',
    endsWith: 'İle Biter',
    equals: 'Eşittir',
    notEquals: 'Eşit Değildir',
    noFilter: 'Filtre Yok',
    lt: 'Küçük',
    lte: 'Küçük veya Eşit',
    gt: 'Büyük',
    gte: 'Büyük veya Eşit',
    dateIs: 'Tarih Şudur',
    dateIsNot: 'Tarih Şu Değildir',
    dateBefore: 'Tarih Şundan Önce',
    dateAfter: 'Tarih Şundan Sonra',
    clear: 'Temizle',
    apply: 'Uygula',
    matchAll: 'Hepsini Eşleştir',
    matchAny: 'Herhangi Birini Eşleştir',
    addRule: 'Kural Ekle',
    removeRule: 'Kural Kaldır',
    accept: 'Evet',
    reject: 'Hayır',
    choose: 'Seç',
    upload: 'Yükle',
    cancel: 'İptal',
    completed: 'Tamamlandı',
    pending: 'Beklemede',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    dayNames: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
    dayNamesShort: ['Paz', 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cts'],
    dayNamesMin: ['Pz', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct'],
    monthNames: [
        'Ocak',
        'Şubat',
        'Mart',
        'Nisan',
        'Mayıs',
        'Haziran',
        'Temmuz',
        'Ağustos',
        'Eylül',
        'Ekim',
        'Kasım',
        'Aralık',
    ],
    monthNamesShort: [
        'Oca',
        'Şub',
        'Mar',
        'Nis',
        'May',
        'Haz',
        'Tem',
        'Ağu',
        'Eyl',
        'Eki',
        'Kas',
        'Ara',
    ],
    chooseYear: 'Yıl Seç',
    chooseMonth: 'Ay Seç',
    chooseDate: 'Tarih Seç',
    prevDecade: 'Önceki On Yıl',
    nextDecade: 'Sonraki On Yıl',
    prevYear: 'Önceki Yıl',
    nextYear: 'Sonraki Yıl',
    prevMonth: 'Önceki Ay',
    nextMonth: 'Sonraki Ay',
    prevHour: 'Önceki Saat',
    nextHour: 'Sonraki Saat',
    prevMinute: 'Önceki Dakika',
    nextMinute: 'Sonraki Dakika',
    prevSecond: 'Önceki Saniye',
    nextSecond: 'Sonraki Saniye',
    am: 'ÖÖ',
    pm: 'ÖS',
    today: 'Bugün',
    weekHeader: 'Hafta',
    firstDayOfWeek: 1,
    showMonthAfterYear: false,
    dateFormat: 'dd/mm/yy',
    weak: 'Zayıf',
    medium: 'Orta',
    strong: 'Güçlü',
    passwordPrompt: 'Şifre giriniz',
    searchMessage: '{0} sonuç mevcut',
    selectionMessage: '{0} öğe seçildi',
    emptySelectionMessage: 'Seçili öğe yok',
    emptySearchMessage: 'Sonuç bulunamadı',
    emptyMessage: 'Mevcut seçenek yok',
    fileChosenMessage: '{0} dosya',
    noFileChosenMessage: 'Seçilen dosya yok',
    aria: {
        trueLabel: 'Doğru',
        falseLabel: 'Yanlış',
        nullLabel: 'Seçilmedi',
        star: '1 yıldız',
        stars: '{star} yıldız',
        selectAll: 'Tüm öğeler seçili',
        unselectAll: 'Tüm öğeler seçili değil',
        close: 'Kapat',
        previous: 'Önceki',
        next: 'Sonraki',
        navigation: 'Gezinme',
        scrollTop: 'En Üst',
        moveTop: 'En Üste Taşı',
        moveUp: 'Yukarı Taşı',
        moveDown: 'Aşağı Taşı',
        moveBottom: 'En Alta Taşı',
        moveToTarget: 'Hedefe Taşı',
        moveToSource: 'Kaynağa Taşı',
        moveAllToTarget: 'Tümünü Hedefe Taşı',
        moveAllToSource: 'Tümünü Kaynağa Taşı',
        pageLabel: 'Sayfa {page}',
        firstPageLabel: 'İlk Sayfa',
        lastPageLabel: 'Son Sayfa',
        nextPageLabel: 'Sonraki Sayfa',
        prevPageLabel: 'Önceki Sayfa',
        rowsPerPageLabel: 'Sayfa Başına Satır',
        jumpToPageDropdownLabel: 'Sayfaya Git Dropdown',
        jumpToPageInputLabel: 'Sayfaya Git Giriş',
        selectRow: 'Satır Seçildi',
        unselectRow: 'Satır Seçilmedi',
        expandRow: 'Satır Genişletildi',
        collapseRow: 'Satır Daraltıldı',
        showFilterMenu: 'Filtre Menüsünü Göster',
        hideFilterMenu: 'Filtre Menüsünü Gizle',
        filterOperator: 'Filtre Operatörü',
        filterConstraint: 'Filtre Kısıtlaması',
        editRow: 'Satırı Düzenle',
        saveEdit: 'Düzenlemeyi Kaydet',
        cancelEdit: 'Düzenlemeyi İptal Et',
        listView: 'Liste Görünümü',
        gridView: 'Izgara Görünümü',
        slide: 'Slayt',
        slideNumber: '{slideNumber}',
        zoomImage: 'Görseli Yakınlaştır',
        zoomIn: 'Yakınlaştır',
        zoomOut: 'Uzaklaştır',
        rotateRight: 'Sağa Döndür',
        rotateLeft: 'Sola Döndür',
    },
};

const primeVueTheme = definePreset(Aura, {
    semantic: {
        primary: {
            50: '#f6fdfb',
            100: '#d2f4ec',
            200: '#afecdd',
            300: '#8ce3ce',
            400: '#68dbbf',
            500: '#45d2b0',
            600: '#3bb396',
            700: '#30937b',
            800: '#267461',
            900: '#1c5446',
            950: '#11352c',
        },
        formField: {
            borderRadius: '{border.radius.sm}',
            paddingX: '1rem',
            paddingY: '0.75rem',
            sm: {
                fontSize: '0.875rem',
                paddingX: '0.875rem',
                paddingY: '0.625rem',
            },
            lg: {
                fontSize: '1.125rem',
                paddingX: '1.125rem',
                paddingY: '0.875rem',
            },
        },
        colorScheme: {
            light: {
                surface: {
                    0: colors.white,
                    100: colors.slate['100'],
                    200: colors.slate['200'],
                    300: colors.slate['300'],
                    400: colors.slate['400'],
                    500: colors.slate['500'],
                    600: colors.slate['600'],
                    700: colors.slate['700'],
                    800: colors.slate['800'],
                    900: colors.slate['900'],
                    950: colors.slate['950'],
                },
            },
            dark: {
                surface: {
                    0: colors.white,
                    100: colors.slate['100'],
                    200: colors.slate['200'],
                    300: colors.slate['300'],
                    400: colors.slate['400'],
                    500: colors.slate['500'],
                    600: colors.slate['600'],
                    700: colors.slate['700'],
                    800: colors.slate['800'],
                    900: colors.slate['900'],
                    950: colors.slate['950'],
                },
                formField: {
                    background: '{surface.700}',
                },
                content: {
                    background: '{surface.800}',
                    hoverBackground: '{surface.700}',
                    borderColor: '{surface.900}',
                    color: '{text.color}',
                },
            },
        },
    },
});

export const primeVueOptions = {
    locale: localeTr,
    theme: {
        preset: primeVueTheme,
        options: {
            darkModeSelector: '.dark',
            cssLayer: {
                name: 'primevue',
                order: 'tailwind-base, primevue, tailwind-utilities',
            },
        },
    },
};
